name: Auto Absent SMS

on:
  workflow_dispatch:
  schedule:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call auto-absent API
        run: |
          curl -sfL -X GET \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            "${{ secrets.VERCEL_URL }}/api/auto-absent"
